/**
 * Build the athenaeum.toml and registry entry for a sub-directory, from the
 * document tree the app already has. Nothing here writes anything: the app is a
 * reader of the registry (ADR-0004), so this produces text for the user to save,
 * mirroring scripts/athenaeum-config.sh.
 */

import type { DocumentSummary } from "../api/types";

export interface Scaffold {
  /** Humanised workspace name from the directory. */
  name: string;
  /** The athenaeum.toml to save at configPath. */
  configToml: string;
  /** The [[workspace]] entry to append to the registry. */
  registryEntry: string;
  /** Absolute path of the workspace directory. */
  absPath: string;
  /** Where the config should be saved. */
  configPath: string;
  /** Whether any Markdown was found under the directory. */
  hasMarkdown: boolean;
}

const NOISE = /^(node_modules|vendor|target|dist|build|\.git|\.github)$/;

export function scaffoldWorkspace(
  dirPath: string,
  workspaceRoot: string,
  documents: DocumentSummary[],
): Scaffold {
  const base = dirPath.split("/").filter(Boolean).pop() ?? dirPath;
  const name = humanize(base);
  const absPath = joinPath(workspaceRoot, dirPath);

  const prefix = `${dirPath}/`;
  const rel = documents
    .filter((d) => d.id.startsWith(prefix))
    .map((d) => d.id.slice(prefix.length));

  const exts = detectExts(rel);

  // Immediate sub-directories that hold Markdown become groups.
  const subHasMarkdown = new Map<string, boolean>();
  for (const id of rel) {
    const slash = id.indexOf("/");
    if (slash < 0) continue;
    const sub = id.slice(0, slash);
    if (NOISE.test(sub)) continue;
    subHasMarkdown.set(sub, (subHasMarkdown.get(sub) ?? false) || isMarkdown(id));
  }
  const groups = [...subHasMarkdown.entries()]
    .filter(([, has]) => has)
    .map(([sub]) => sub)
    .sort();

  return {
    name,
    configToml: buildToml(name, exts, groups),
    registryEntry: `[[workspace]]\nname = "${escapeToml(name)}"\npath = "${escapeToml(absPath)}"\n`,
    absPath,
    configPath: joinPath(absPath, "athenaeum.toml"),
    hasMarkdown: rel.some(isMarkdown),
  };
}

function detectExts(relIds: string[]): string[] {
  const exts: string[] = [];
  if (relIds.some((id) => id.endsWith(".md"))) exts.push("md");
  if (relIds.some((id) => id.endsWith(".markdown"))) exts.push("markdown");
  return exts.length > 0 ? exts : ["md"];
}

function isMarkdown(id: string): boolean {
  return id.endsWith(".md") || id.endsWith(".markdown");
}

function buildToml(name: string, exts: string[], groups: string[]): string {
  const include = exts.map((e) => `  "**/*.${e}",`).join("\n");
  const writable = [...exts.map((e) => `  "**/*.${e}",`), `  "assets/**",`, `  ".athenaeum/shared/**",`].join("\n");

  let toml = `# Generated by Athenaeum. Edit freely; this is a starting point.
schema_version = 1
name = "${escapeToml(name)}"
root = "."

include = [
${include}
]

exclude = [
  "**/node_modules/**",
  "**/vendor/**",
  "**/target/**",
  "**/dist/**",
  "**/build/**",
  ".git/**",
]

[documents]
raw_html = false
wiki_links = true
footnotes = true
callouts = true
math = true
mermaid = true
front_matter = ["yaml", "toml"]

[assets]
directory = "assets"
allow_remote = true

[search]
enabled = true

[git]
enabled = true

[security]
writable = [
${writable}
]
allow_external_reads = false
`;

  const seen = new Set<string>();
  for (const sub of groups) {
    let id = slugify(sub) || "group";
    let unique = id;
    let n = 2;
    while (seen.has(unique)) unique = `${id}-${n++}`;
    seen.add(unique);
    const patterns = exts.map((e) => `"${escapeToml(sub)}/**/*.${e}"`).join(", ");
    toml += `\n[[groups]]\nid = "${escapeToml(unique)}"\ntitle = "${escapeToml(humanize(sub))}"\npatterns = [${patterns}]\n`;
  }

  toml += `\n[relationships.front_matter]\nfields = ["related", "implements", "supersedes"]\n`;
  return toml;
}

function humanize(s: string): string {
  return s
    .replace(/[-_]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function escapeToml(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function joinPath(a: string, b: string): string {
  return `${a.replace(/\/$/, "")}/${b.replace(/^\//, "")}`;
}
